language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2 DOCKER_USERNAME=ahasanin DOCKER_PASSWORD='7asanin$$' KUBE_CONFIG=YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VONVJF
TkRRV0pEWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBW
UldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkpkMDFFVVhsT1JFVjRUWHBy
ZVUxc2IxaEVWRTEzVFVSUmVVMXFSWGhOZW10NVRXeHZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZ
VE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJW
QkJSRU5EUVZGdlEyZG5SVUpCU25CcENsUXlhR3RTSzBzNE5rUTNXbVJrUzBWeVRESlNWa2N4TVRC
Rk0yVkdVMGxNZVdOd1VYQnNhbnBNVVhrdlQycHBhMGd3TjJKdFlVaHRPRU55V0ZNMkwzRUthVlky
Ym0xM2JUQndkR3gyY2xrclZtODFZVnBIY0dwRkt6ZDVZbE5YY0c5aWRrODVlVFpKZUVsMU5XOXZV
MXA0WmpOcE1VeHBUMFZvUjNKRWNVaHRSZ3AyYUVkalIyZ3hiR2x1TXpGaGFpODJhbnAxVGpCS1ZH
cDJVbkkxUWxacWFtaENXRkF5TDFsT1VqWnRTbGRLYmtaVVUyMXlSMlozWnpNMloxZ3hPR2xyQ2ta
MFlVdFpObFZOYVZkTlRDdFdkblphUkd0Q01qY3dlRkpKUm01elQzcEtWbnBvTXpBelNWQnpjWEF2
U0ZCYVNqbDFSVkpPTjNZM1JWTk5SbG92WW1rS2RsVmlhVzlrTHpSc1RpdEdNSEZKZWxsUlZrZHlX
WEowVXpGaWJtOW9iekJ1TUUxTlFrOWhOM1EyVkUxV2FpODFLMk5xTjJONFZHTjNWR1Z3YlVOblp3
cHpRMlpVVVhaNVExUnBUakkxUWk5a1QxTXdRMEYzUlVGQllVMXFUVU5GZDBSbldVUldVakJRUVZG
SUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBSUldVcExiMXBK
YUhaalRrRlJSVXhDVVVGRVoyZEZRa0ZKUVdad2JuZFVUVmxsUmtWdldYTTFZbFExWjNKbGNrUlZR
a2dLVUVrdmF6ZEtNelU1YVd0dVZHMHZSSEphUWs5T09EWnZOR1l3ZUhac05uWnpVMEo1WmpOaFpt
RnBlbk5uY0VsWkwycE5hVWhoZVdscVJrVlVRemMwT0FwalduSTVPRE56VTNacGVYUlBaMWxRUTNG
cmNsTlpVWGR3V0hrMVkxZ3hWRnB1YXk5emJFSnFSelZDYXpKT1lXOWpibmhIUTNwaldGTTFZVFl6
UVhGQ0NsWmhWR2xFWjBobVdIcGhTWE5IUVdwNVN6QjFha2hLYkZOQmIxcG5SV3RMTWtsaE5VdFNh
VzgyTUVJMmEydE9URk52VTBoQ1FqaHlibFpRZW1sRE9Vc0tkRFpzY1ZGV0szUlpZamhrZWpSemVT
OTVhV2xoY1VsUldWazNNMjgzYmxCTFVFbDNhSHA0ZWpOd1JWRjJRV1F6YkZSNGRtaHpLMk5qY1ZK
Mk0wTmlaZ3A0ZGxjM1NXMVhPVU4xUW1nMFUxaHRWbVJsZDJkWmVFWmhZbmwzZDNaNVZrRTBSVEpw
ZEZvNE9GSlhTbVJ1V25RMk5rdE9kWGhsY2pCT1NUMEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJW
RVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly9rdWJlcm5ldGVzLmRvY2tlci5pbnRlcm5h
bDo2NDQzCiAgbmFtZTogZG9ja2VyLWRlc2t0b3AKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNs
dXN0ZXI6IGRvY2tlci1kZXNrdG9wCiAgICB1c2VyOiBkb2NrZXItZGVza3RvcAogIG5hbWU6IGRv
Y2tlci1kZXNrdG9wCi0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGRvY2tlci1kZXNrdG9wCiAgICB1
c2VyOiBkb2NrZXItZGVza3RvcAogIG5hbWU6IGRvY2tlci1mb3ItZGVza3RvcApjdXJyZW50LWNv
bnRleHQ6IGRvY2tlci1kZXNrdG9wCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczoge30KdXNlcnM6
Ci0gbmFtZTogZG9ja2VyLWRlc2t0b3AKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRh
dGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVU01UkVORFFXUjVa
MEYzU1VKQlowbEpZbEJpTmxwQ1YwUlhNbU4zUkZGWlNrdHZXa2xvZG1OT1FWRkZURUpSUVhkR1ZF
VlVUVUpGUjBFeFZVVUtRWGhOUzJFelZtbGFXRXAxV2xoU2JHTjZRV1ZHZHpCNVRVUkJNRTFxVVho
TlZFMDFUV3BLWVVaM01IbE5WRUV4VFVSamQwMTZSVFZOUkZKaFRVUlplQXBHZWtGV1FtZE9Wa0pC
YjFSRWJrNDFZek5TYkdKVWNIUlpXRTR3V2xoS2VrMVNjM2RIVVZsRVZsRlJSRVY0U210aU1rNXlX
bGhKZEZwdE9YbE1WMUpzQ21NeWREQmlNMEYzWjJkRmFVMUJNRWREVTNGSFUwbGlNMFJSUlVKQlVW
VkJRVFJKUWtSM1FYZG5aMFZMUVc5SlFrRlJRM0l3ZWxKWWMxUnVXbUpKYkdJS2RIRTRjblkzTW01
UFMzcFpZMmsxVlVaNVRUZFRSamxFVkZSclpsTmpOVlV5V25aaWRsQnFiRGxWUlhNMWMxWTFVek5H
Vm5CallWQmlZakZ0YjJOT1Z3cERPR1IwY25OM1lsRlJRV3hpYTNnNVNDOXVXR1paVDNCQmEzZGxN
V0V6TVd0RFlqaG5jVlp3Ym1wSllsUmFjamN2VlV4aU16SkZUUzlTY0ZsWGVIRnpDa1J3Y3l0UVZX
UjBURmxEZEV3eVRsWlplbm8wYVVsb2R6QklZbkJzVjJGWVNVMVlNbUo2ZFhCU1RucGlWUzlwUm1o
TlYySmxaVFJaVWt0TFJUYzFPVGtLUjA1dEwwVkNiWFZaVTJaaFRsUkZMMnB4UmxSWVpWQlJZMjFo
ZVdwRmNHOWxUWGhpTnpBMmRVaGlTemROVWtsWlNreFZZMUp2U1VGTE5tWnJXRVUzZVFwMGMwODNP
R2RoYjFRMVFrNW9lRlFyVlRoV05qUjZOV1pWZHpaSlExVjZaalV3TmxGTU5qWnpOR2xhWlM5VVJV
bFhjM0pZY1ROQmF6UTBhMjAzU1N0cUNucE1ibHBJU2xSaVFXZE5Ra0ZCUjJwS2VrRnNUVUUwUjBF
eFZXUkVkMFZDTDNkUlJVRjNTVVp2UkVGVVFtZE9Wa2hUVlVWRVJFRkxRbWRuY2tKblJVWUtRbEZq
UkVGcVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVhOR1FVRlBRMEZSUlVGQmQxVjZRWFZ5UVZNdmJsaEpW
MVZzUmpsS2VWUlhWVTAwZFdwQ1ltaFBPUXBTY0VWVlkwRkRaRlkxWm1kcWJrSXlhQzl0VWxWaU16
UmlVMHRIZG1kcVZuZEthMnQ1UVdnNFUyOTFiV3BRVEVsclpsUjBhUzlxTVZJMlRUZENNRXMyQ2xZ
MVRsUkNVMkpUUVZwU2MyOUhRV3d2U2tKM2RUWk1WSHAwS3pkMmVtWlVkalJZWjJWT1ZqZEJLM0F5
Y25oQlEwWnBOMFpEY1U5TlYweDJiR2RKVFVVS1RrUkJlR3RsVDFwaFZuSXJTRlJ1ZEZwT1lsaGFS
RkI1UlV4ck1WVmtiVEZoUzBsM2NXNUVTRzV1VlVoMGVEVnhTM2cyU2twbFRHbENjM1JvYVVKUVZR
cFNhRnBKVHpGUVVVMDVWbmg1VVVOcGFubEhiRmxNWmxaTlFVUlZiSEpQVWt0a2JUbFZla3REVTJK
YWJFdEJNemQwVkZZek1GVjFTMGxTTUZndmJEaExDak5pZUVkV1JuSldSVzVxVkhGc2FHeE1TWGhR
VEc0Mk5VSTFSemd3T0VaUlpHVXlUV2R6ZFhGUVJVbElZMWw0T0hOck0ydFpRVDA5Q2kwdExTMHRS
VTVFSUVORlVsUkpSa2xEUVZSRkxTMHRMUzBLCiAgICBjbGllbnQta2V5LWRhdGE6IExTMHRMUzFD
UlVkSlRpQlNVMEVnVUZKSlZrRlVSU0JMUlZrdExTMHRMUXBOU1VsRmNFRkpRa0ZCUzBOQlVVVkJj
VGxOTUZZM1JUVXlWM2xLVnpkaGRrczNLemx3ZW1sek1raEpkVlpDWTJwUE1HaG1VVEF3TlVnd2Jr
OVdUbTFpQ2pJM2VqUTFabFpDVEU5aVJtVlZkSGhXWVZoSGFqSXlPVnB4U0VSV1ozWklZbUUzVFVj
d1JVRktWelZOWmxJdk5URXpNa1J4VVVwTlNIUlhkRGxhUVcwS0wwbExiR0ZhTkhsSE1ESmhLeTh4
UXpJNU9XaEVVREJoVjBaellYSkJObUpRYWpGSVlsTXlRWEpUT1dwV1YwMDRLMGxwU1dOT1FqSTJX
bFp0YkhsRVJnbzViVGczY1ZWVVl6SXhVRFJvV1ZSR2JUTnVkVWRGVTJsb1R5dG1abEpxV25aNFFW
cHliVVZ1TW1wVmVGQTBObWhWTVROcU1FaEtiWE52ZUV0aFNHcE5DbGNyT1U5eWFESjVkWHBGVTBk
RFV6RklSV0ZEUVVOMWJqVkdlRTg0Y21KRWRTOUpSM0ZGSzFGVVdXTlZMMnhRUm1WMVRTdFlNVTFQ
YVVGc1RUTXJaRThLYTBNcmRYSlBTVzFZZGpCNFEwWnlTekUyZEhkS1QwOUtTblY1VUc4NGVUVXlV
bmxWTW5kSlJFRlJRVUpCYjBsQ1FWRkRWakZMY0VRdllYSjNVMXBFVGdwb1RsQnFWbTFRVDNWalJX
WlVVa2hTUTJkM1V6SmtNRmxHZGt4RmMyUjBWMkZvZEdFeFkwcEZOVVZTWkVoNU56ZDNhVzF0UVdS
VVVIQlhXVkJhVDJWekNqRk5RMjFwUmtrM1VXTmpZVE5NSzJWTVNTOHdkRTlLYlUxcVlXMW1URmxu
T1M4M1NFZHFWMkpxTDAxd2F6bGhaQzluTm1KS1NVeEJhazFUTkZneGF6SUtlRGxZWm5oQ1psRjNS
MnRCYlRrMFIza3lObFJYY0hRdmNFbHFUWHBoYWt0b0swNDFkRkJuU0haSmVIVjNUR0U0TVRCdVJW
TmhWV3MwZFhOdllWZGtlUXBGU0ZWM05EVmlTVlZsTm5WSVJGRkxaamhVVXpkdFRWSnNOamR3VmpO
SlJrdDZjVTlOWXpsbVNIaHFNa0p5V1hoeVltdEViakZvTkROSVkzUnZkMUZxQ2s1M1NYcE9lbGhJ
ZDJGV2VEYzNZVWRMYzBKNU9FRmhjbEJZYjI0ck5XbE1XVlJOWVZJeEsxcE1NelIzTWxaQmN5OU1U
bE01ZVVGYWJuaENVbEl3Y2k4S01FVmFWRU01U0doQmIwZENRVTVPZERaSVYzRlpVeTl3YUZwa1lt
ZHpOM1pRZUd0RldFVlZOamd3VEZKa1ZUQmlSRWRUV1hneFdGVm1Oa0pxUzNCVVdRbzBiMVp4ZURk
d1ExQlZVWE5rVHpKcWVrbFJjR0pvU2pWYWMwOXNWWFpsVEdoalJIbEViVlZ3V25sdlF6RnpNbUZz
UjFGdVZIWTBaR2NyVVU1bVVGQXZDbEpRTDNWa1lXdDZhVFZGYkdWdWJ6SjRkV2cyZVM5YVNUbEtV
MUJhYmxaVVdtOXJhemR0WWtaQ1QxRmFURkpPY20xd1RYUjFPRVJ1UVc5SFFrRk9RVXdLTDJaYVow
aDRhWFV4UjBSeE5VZGFkVlJvYjJkc2NEZEpaR1ZxUkVJd2JGSnNVVkpaTlc1TVJsVXdkMjV4ZDBj
emNXY3djVFF4TUdKV2NEZ3ZlRTV1WmdwS2NHZGlXSFI0VjI0ek9FNHZRMkpuUjIxSGIyWlJkRlUz
VkhweE1rNDRaV1p4UkRWQ2RuQkpjRXh6VjNCS1ZsVXZVazFUTlRCaU1UVmxVV0Y0VG5wR0NtSm5Z
M05HVERkaVR6VkpNRWhRYTJwbllsQXpSM0ZFYjB4aWNGTlJTRVpRY2tKblVuRnBiblJCYjBkQ1FV
dFhWV1JNU0RVemFWVkZjMFl2UzBKb1lVUUtNMXBzT1VKaWIyVkpZbUphYWxKRU1uUjFlblJxVjJK
V2FHRkpXa28xWW5Ob0wwcFBiblExY1RBNGNGcFBjbGRHVTNwNlVuRlhaVVZrWjNWUmNGQndRd28x
Vm5kdE9WVnJZV1JNVnpsQ1dGbzVjMlZ6UW5ObFdtNVFVWGhVTVN0RVMzTk5TSGxuVjJ0cFpXaEpV
a1pQYzNwcVVFVjVaMmgwSzBwVVZsaFlUR3hVQ25WSlFqbFZUWFJvVkhGU1NWcDZia2hWYjFscVJX
VkNVRUZ2UjBGa1kxSXdSRVZWTlVaU1dGTk1kRXRKVnpsMFVUVnpWbEIyWVRSdU5FbDVWakJXUlZn
S1JUVkVibFZyZVZVM1IxVkJSR3RpVkZGblZHNUZNSFJ2WVRGclJIRXphMEZPWkZrMGFXMHlWMlEy
ZFVrNGRFTnJNMjFqY2poWlFYWnJkVFF4ZFZsa1pncHJkWFZyYjFsVlFtbHpOREJsUkhaV2VtcG9S
RXAzTkVoQ2JYRkplVnBuVVhkdmNWaGhOM0JoVEVaaVNHdzVaMkpyWVROMFMzVjVSRUpvWlU1V2VH
Tk5DbWxqZEcxRlltdERaMWxDZDFkSWFGRk1SWGt6Y1dKelJIQm9jelF3V0ZoUFRtNXVlRlpSYTNW
d1pUQTBjVVZtVG5wc2FEUkpSM1IxYml0S09GUjZiMmNLUlUxME0wVTVWRTFEYUdnMlJFaHNjbll5
VjJ3elpVdHpVWEIwVlc5aFNWazNiakpaUXpoVE4xbFBWVWcwVFRscWRsVnJORzFHVWpobWJVaDFZ
bE41YmdwUVkySnBVMW9yVDJzMVVFNW1PRk5oYkhOWmNUSjNVbEEyY2twdWQzUkpiak5KYUVGMlZ6
TmpURzV5YjNGQldWRmlha1JvVjJjOVBRb3RMUzB0TFVWT1JDQlNVMEVnVUZKSlZrRlVSU0JMUlZr
dExTMHRMUW89Cg==
before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-Linux-x86_64> docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config




install:
  - kubectl apply -f udacity-c3-deployment/k8s/aws-secret.yaml
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel 
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml push
  - kubectl apply -f udacity-c3-deployment/k8s/env-configmap.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-feed-serivice.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-user-serivice.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/frontend-serivice.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/reverseproxy-serivice.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-feed-deployment.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-user-deployment.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/frontend-deployment.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/reverseproxy-deployment.yaml
